# Generated by Django 2.0.4 on 2018-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_data',
            name='search_text',
            field=models.TextField(max_length=500),
        ),
    ]
